UBUNTU: tools -- upgrade to common generic helper
In order to allow us to have tools from both the current releases and
newer LTS backport releases we need the updated generic helper which
understands all possible locations.  At the same time take the
opportunity to standardise on a single helper.

BugLink: http://bugs.launchpad.net/bugs/1205284
Signed-off-by: Andy Whitcroft <apw@canonical.com>
Acked-by: Stefan Bader <stefan.bader@canonical.com>
Signed-off-by: Tim Gardner <tim.gardner@canonical.com>

diff --git a/debian/tools/generic b/debian/tools/generic
--- a/debian/tools/generic
+++ b/debian/tools/generic
@@ -1,16 +1,30 @@
 #!/bin/bash
 full_version=`uname -r`
 
+# First check for a fully qualified version.
+this="/usr/lib/linux-tools/$full_version/`basename $0`"
+if [ -f "$this" ]; then
+	exec "$this" "$@"
+fi
+
+# FALLBACK for older kernel layouts
 # Removing flavour from version i.e. generic or server.
 flavour_abi=${full_version#*-}
 flavour=${flavour_abi#*-}
 version=${full_version%-$flavour}
 this="$0_$version"
-
-if [ ! -f "$this" ]; then
-    echo "$this not found" >&2
-    echo "You may need to install linux-tools-$version" >&2
-    exit 2
+if [ -f "$this" ]; then
+	exec "$this" "$@"
 fi
 
-exec "$this" "$@"
+# If we have the appropriate package installed but no
+# tool then the tool does not exist.
+if [ -d "/usr/lib/linux-tools/$full_version" ]; then
+	echo "`basename $0` not available for kernel $version" >&2
+	exit 2
+fi
+
+# Give them a hint as to what to install.
+echo "`basename $0` not found for kernel $version" >&2
+echo "You may need to install linux-tools-$version-$flavour" >&2
+exit 2
